### ISSUE TITLE
Completare Create e Edit (RF2)

### ISSUE THREAD

**Issue by pizzi9523** [Andretreccia/boolbnb#34]
Implementare la scelta dei servizi e lo script per il salvataggio di latitudine e longitudine

**Comment by pizzi9523** [comment]
Implementare la scelta dei servizi e lo script per il salvataggio di latitudine e longitudine

**Comment by Andretreccia** [comment]
Fixare i dati gia esistenti nell'edit

**Comment by lumilio** [comment]
ho aggiunto i bagni, stanze, camere e mq  dentro edit, create e show.

non ho fatto la checkbox visibility

**Comment by lumilio** [comment]
checkbox visibility fatta ma senza stile
